// Generated by scripts/generate-visual-catalog.mjs.
// Do not hand-edit; update the reviewed selections in the generator instead.

export type GeneratedVisualCandidate = {
  letter: string;
  releaseId: string;
  title: string;
  artist: string;
  detailUrl: string;
  localCoverUrl: string;
};

export const GENERATED_VISUAL_CANDIDATES: Record<
  string,
  GeneratedVisualCandidate[]
> = {
  "A": [
    {
      "letter": "A",
      "releaseId": "07909b1e-18e0-4ba9-9295-7dd1fd360b52",
      "title": "a",
      "artist": "BIGBANG",
      "detailUrl": "https://musicbrainz.org/release/07909b1e-18e0-4ba9-9295-7dd1fd360b52",
      "localCoverUrl": "/covers/visual-candidates/a-3.jpg"
    },
    {
      "letter": "A",
      "releaseId": "f0a5489d-8cec-43ed-abd5-3d0099c2aebf",
      "title": "A",
      "artist": "Mazzoll, Arhythmic Perfection",
      "detailUrl": "https://musicbrainz.org/release/f0a5489d-8cec-43ed-abd5-3d0099c2aebf",
      "localCoverUrl": "/covers/visual-candidates/a-4.jpg"
    },
    {
      "letter": "A",
      "releaseId": "7e9fd860-196c-47d6-8377-d6882d1aeb46",
      "title": "A",
      "artist": "Ryan Preston",
      "detailUrl": "https://musicbrainz.org/release/7e9fd860-196c-47d6-8377-d6882d1aeb46",
      "localCoverUrl": "/covers/visual-candidates/a-5.jpg"
    }
  ],
  "B": [
    {
      "letter": "B",
      "releaseId": "5f64edff-b4a9-4206-b015-af4221134edb",
      "title": "B",
      "artist": "Noah T",
      "detailUrl": "https://musicbrainz.org/release/5f64edff-b4a9-4206-b015-af4221134edb",
      "localCoverUrl": "/covers/visual-candidates/b-1.jpg"
    },
    {
      "letter": "B",
      "releaseId": "3ae52247-1492-4e59-ae21-152151ea2bdb",
      "title": "B",
      "artist": "LifeMod",
      "detailUrl": "https://musicbrainz.org/release/3ae52247-1492-4e59-ae21-152151ea2bdb",
      "localCoverUrl": "/covers/visual-candidates/b-2.jpg"
    },
    {
      "letter": "B",
      "releaseId": "6bb4eaa8-5ec2-40c2-91cc-dcc47243cbba",
      "title": "B",
      "artist": "System",
      "detailUrl": "https://musicbrainz.org/release/6bb4eaa8-5ec2-40c2-91cc-dcc47243cbba",
      "localCoverUrl": "/covers/visual-candidates/b-3.jpg"
    },
    {
      "letter": "B",
      "releaseId": "f3334064-560d-4439-86a1-08584e8d6766",
      "title": "B",
      "artist": "Beat Assailant",
      "detailUrl": "https://musicbrainz.org/release/f3334064-560d-4439-86a1-08584e8d6766",
      "localCoverUrl": "/covers/visual-candidates/b-4.jpg"
    },
    {
      "letter": "B",
      "releaseId": "f992b4d5-7c47-435a-8bad-c90751fac255",
      "title": "B",
      "artist": "SikitikiS",
      "detailUrl": "https://musicbrainz.org/release/f992b4d5-7c47-435a-8bad-c90751fac255",
      "localCoverUrl": "/covers/visual-candidates/b-5.jpg"
    }
  ],
  "C": [
    {
      "letter": "C",
      "releaseId": "62a87e13-1d3f-4364-bcc0-97db17ddeb2e",
      "title": "C",
      "artist": "Tensal™",
      "detailUrl": "https://musicbrainz.org/release/62a87e13-1d3f-4364-bcc0-97db17ddeb2e",
      "localCoverUrl": "/covers/visual-candidates/c-2.jpg"
    },
    {
      "letter": "C",
      "releaseId": "7ffaab72-ccf5-43f4-b76f-a651867370eb",
      "title": "C",
      "artist": "Jimmy Castor",
      "detailUrl": "https://musicbrainz.org/release/7ffaab72-ccf5-43f4-b76f-a651867370eb",
      "localCoverUrl": "/covers/visual-candidates/c-4.jpg"
    },
    {
      "letter": "C",
      "releaseId": "4be6ec80-fb98-4e16-a5fe-a1f1fa284c60",
      "title": "C",
      "artist": "Anders Bergcrantz Quartet",
      "detailUrl": "https://musicbrainz.org/release/4be6ec80-fb98-4e16-a5fe-a1f1fa284c60",
      "localCoverUrl": "/covers/visual-candidates/c-5.jpg"
    }
  ],
  "D": [
    {
      "letter": "D",
      "releaseId": "b3fed08f-93d6-44fc-a13c-a5569416aee0",
      "title": "D",
      "artist": "BIGBANG",
      "detailUrl": "https://musicbrainz.org/release/b3fed08f-93d6-44fc-a13c-a5569416aee0",
      "localCoverUrl": "/covers/visual-candidates/d-1.jpg"
    },
    {
      "letter": "D",
      "releaseId": "758bb67c-9d7a-4c93-b5f4-c69220a68edb",
      "title": "D",
      "artist": "Codeine",
      "detailUrl": "https://musicbrainz.org/release/758bb67c-9d7a-4c93-b5f4-c69220a68edb",
      "localCoverUrl": "/covers/visual-candidates/d-2.jpg"
    },
    {
      "letter": "D",
      "releaseId": "78f10a03-5788-4bba-81f3-17aa9725433f",
      "title": "D",
      "artist": "Tarika",
      "detailUrl": "https://musicbrainz.org/release/78f10a03-5788-4bba-81f3-17aa9725433f",
      "localCoverUrl": "/covers/visual-candidates/d-3.jpg"
    },
    {
      "letter": "D",
      "releaseId": "dc16ccbf-ab90-4b3e-86a0-4e1b1b2404bb",
      "title": "D",
      "artist": "White Denim",
      "detailUrl": "https://musicbrainz.org/release/dc16ccbf-ab90-4b3e-86a0-4e1b1b2404bb",
      "localCoverUrl": "/covers/visual-candidates/d-4.jpg"
    },
    {
      "letter": "D",
      "releaseId": "59c23764-199d-4f05-8b3a-18dca4ac0c77",
      "title": "D",
      "artist": "Hex Rx",
      "detailUrl": "https://musicbrainz.org/release/59c23764-199d-4f05-8b3a-18dca4ac0c77",
      "localCoverUrl": "/covers/visual-candidates/d-5.jpg"
    }
  ],
  "E": [
    {
      "letter": "E",
      "releaseId": "43dcd88b-268e-4e5c-b045-9bc02547d545",
      "title": "E",
      "artist": "BIGBANG",
      "detailUrl": "https://musicbrainz.org/release/43dcd88b-268e-4e5c-b045-9bc02547d545",
      "localCoverUrl": "/covers/visual-candidates/e-1.jpg"
    },
    {
      "letter": "E",
      "releaseId": "4311b90f-99c6-44b3-8bc1-a648f43bf189",
      "title": "E",
      "artist": "Kenneths",
      "detailUrl": "https://musicbrainz.org/release/4311b90f-99c6-44b3-8bc1-a648f43bf189",
      "localCoverUrl": "/covers/visual-candidates/e-2.jpg"
    },
    {
      "letter": "E",
      "releaseId": "5d151005-2177-404a-976b-2a7491ebf4dd",
      "title": "E",
      "artist": "E",
      "detailUrl": "https://musicbrainz.org/release/5d151005-2177-404a-976b-2a7491ebf4dd",
      "localCoverUrl": "/covers/visual-candidates/e-3.jpg"
    },
    {
      "letter": "E",
      "releaseId": "fa2f6c03-8e68-4597-8269-af101302eae4",
      "title": "E",
      "artist": "Diamond Black Hearted Boy",
      "detailUrl": "https://musicbrainz.org/release/fa2f6c03-8e68-4597-8269-af101302eae4",
      "localCoverUrl": "/covers/visual-candidates/e-4.jpg"
    },
    {
      "letter": "E",
      "releaseId": "9c5ef1e5-1a47-405f-92cc-157241234186",
      "title": "E",
      "artist": "Michael Aristotle",
      "detailUrl": "https://musicbrainz.org/release/9c5ef1e5-1a47-405f-92cc-157241234186",
      "localCoverUrl": "/covers/visual-candidates/e-5.jpg"
    }
  ],
  "F": [
    {
      "letter": "F",
      "releaseId": "da17bd65-5dca-47b8-8b46-126ea501bff4",
      "title": "F",
      "artist": "Pedro Abrunhosa & Os Bandemónio",
      "detailUrl": "https://musicbrainz.org/release/da17bd65-5dca-47b8-8b46-126ea501bff4",
      "localCoverUrl": "/covers/visual-candidates/f-1.jpg"
    },
    {
      "letter": "F",
      "releaseId": "84894286-9733-4029-a55b-b6f249e60c97",
      "title": "f",
      "artist": "後藤沙緒里",
      "detailUrl": "https://musicbrainz.org/release/84894286-9733-4029-a55b-b6f249e60c97",
      "localCoverUrl": "/covers/visual-candidates/f-2.jpg"
    },
    {
      "letter": "F",
      "releaseId": "21c1fb5a-2527-40a5-b9d8-45a917c8bb08",
      "title": "F",
      "artist": "PBK, Roe",
      "detailUrl": "https://musicbrainz.org/release/21c1fb5a-2527-40a5-b9d8-45a917c8bb08",
      "localCoverUrl": "/covers/visual-candidates/f-3.jpg"
    },
    {
      "letter": "F",
      "releaseId": "2096f753-477c-48c2-957b-8e870906634b",
      "title": "f",
      "artist": "サラ・オレイン",
      "detailUrl": "https://musicbrainz.org/release/2096f753-477c-48c2-957b-8e870906634b",
      "localCoverUrl": "/covers/visual-candidates/f-4.jpg"
    },
    {
      "letter": "F",
      "releaseId": "d8895107-14e4-4128-946b-8e6463f312cb",
      "title": "F",
      "artist": "LifeMod",
      "detailUrl": "https://musicbrainz.org/release/d8895107-14e4-4128-946b-8e6463f312cb",
      "localCoverUrl": "/covers/visual-candidates/f-5.jpg"
    }
  ],
  "G": [
    {
      "letter": "G",
      "releaseId": "fb1ac900-8a0f-49c9-9601-caef837d86e8",
      "title": "G",
      "artist": "Malibu Stacy",
      "detailUrl": "https://musicbrainz.org/release/fb1ac900-8a0f-49c9-9601-caef837d86e8",
      "localCoverUrl": "/covers/visual-candidates/g-1.jpg"
    },
    {
      "letter": "G",
      "releaseId": "8734ec3c-f9c6-4444-9560-c678e701d14b",
      "title": "G",
      "artist": "Forehead",
      "detailUrl": "https://musicbrainz.org/release/8734ec3c-f9c6-4444-9560-c678e701d14b",
      "localCoverUrl": "/covers/visual-candidates/g-3.jpg"
    },
    {
      "letter": "G",
      "releaseId": "c0573038-4359-40ef-9de1-dec9fbfb3160",
      "title": "G",
      "artist": "minus(−)",
      "detailUrl": "https://musicbrainz.org/release/c0573038-4359-40ef-9de1-dec9fbfb3160",
      "localCoverUrl": "/covers/visual-candidates/g-4.jpg"
    },
    {
      "letter": "G",
      "releaseId": "76d2effd-f1b0-402a-a314-009e816e4bc1",
      "title": "G",
      "artist": "Gerald Albright",
      "detailUrl": "https://musicbrainz.org/release/76d2effd-f1b0-402a-a314-009e816e4bc1",
      "localCoverUrl": "/covers/visual-candidates/g-5.jpg"
    }
  ],
  "H": [
    {
      "letter": "H",
      "releaseId": "d273d28e-6a76-48a7-bb70-99e60bc0ec88",
      "title": "H",
      "artist": "Huski",
      "detailUrl": "https://musicbrainz.org/release/d273d28e-6a76-48a7-bb70-99e60bc0ec88",
      "localCoverUrl": "/covers/visual-candidates/h-2.jpg"
    },
    {
      "letter": "H",
      "releaseId": "c6d33fe6-6dd3-45c4-8c1c-aa4ff2d6e127",
      "title": "h",
      "artist": "Taku Sugimoto, Cristián Alvear",
      "detailUrl": "https://musicbrainz.org/release/c6d33fe6-6dd3-45c4-8c1c-aa4ff2d6e127",
      "localCoverUrl": "/covers/visual-candidates/h-3.jpg"
    },
    {
      "letter": "H",
      "releaseId": "758fe7df-432d-4f8f-b1fc-bc8d5db617c8",
      "title": "H",
      "artist": "Husalah",
      "detailUrl": "https://musicbrainz.org/release/758fe7df-432d-4f8f-b1fc-bc8d5db617c8",
      "localCoverUrl": "/covers/visual-candidates/h-4.jpg"
    }
  ],
  "I": [
    {
      "letter": "I",
      "releaseId": "5cc9d74e-8e72-4dec-8de6-51afe13ff42c",
      "title": "I",
      "artist": "TAEYEON",
      "detailUrl": "https://musicbrainz.org/release/5cc9d74e-8e72-4dec-8de6-51afe13ff42c",
      "localCoverUrl": "/covers/visual-candidates/i-1.jpg"
    },
    {
      "letter": "I",
      "releaseId": "b3f7a97e-43cd-4456-9013-b8c30a7b1621",
      "title": "I",
      "artist": "Felix Jaehn",
      "detailUrl": "https://musicbrainz.org/release/b3f7a97e-43cd-4456-9013-b8c30a7b1621",
      "localCoverUrl": "/covers/visual-candidates/i-3.jpg"
    },
    {
      "letter": "I",
      "releaseId": "256bbffa-7d0a-3665-8e5d-3eebc20568c4",
      "title": "i",
      "artist": "The Magnetic Fields",
      "detailUrl": "https://musicbrainz.org/release/256bbffa-7d0a-3665-8e5d-3eebc20568c4",
      "localCoverUrl": "/covers/visual-candidates/i-4.jpg"
    },
    {
      "letter": "I",
      "releaseId": "7d915596-a321-40e0-97fc-9d6912706891",
      "title": "I",
      "artist": "Mika Nakashima",
      "detailUrl": "https://musicbrainz.org/release/7d915596-a321-40e0-97fc-9d6912706891",
      "localCoverUrl": "/covers/visual-candidates/i-5.jpg"
    }
  ],
  "J": [
    {
      "letter": "J",
      "releaseId": "db36c45b-2b1f-4217-af6c-11a088d0f3da",
      "title": "J",
      "artist": "LifeMod",
      "detailUrl": "https://musicbrainz.org/release/db36c45b-2b1f-4217-af6c-11a088d0f3da",
      "localCoverUrl": "/covers/visual-candidates/j-1.jpg"
    },
    {
      "letter": "J",
      "releaseId": "2b547c1b-e2f5-4148-8139-6932bb96ab26",
      "title": "J",
      "artist": "Hot Dad",
      "detailUrl": "https://musicbrainz.org/release/2b547c1b-e2f5-4148-8139-6932bb96ab26",
      "localCoverUrl": "/covers/visual-candidates/j-3.jpg"
    },
    {
      "letter": "J",
      "releaseId": "5485679a-b851-497d-8b59-bdf5401d23ce",
      "title": "J",
      "artist": "Tensal",
      "detailUrl": "https://musicbrainz.org/release/5485679a-b851-497d-8b59-bdf5401d23ce",
      "localCoverUrl": "/covers/visual-candidates/j-5.jpg"
    }
  ],
  "K": [
    {
      "letter": "K",
      "releaseId": "43a0da18-4435-40cb-98e0-4034ba7fc831",
      "title": "K",
      "artist": "Korpi Ensemble",
      "detailUrl": "https://musicbrainz.org/release/43a0da18-4435-40cb-98e0-4034ba7fc831",
      "localCoverUrl": "/covers/visual-candidates/k-1.jpg"
    },
    {
      "letter": "K",
      "releaseId": "14df2b01-0619-4676-adef-1c0f320d4029",
      "title": "K",
      "artist": "Directors Cut",
      "detailUrl": "https://musicbrainz.org/release/14df2b01-0619-4676-adef-1c0f320d4029",
      "localCoverUrl": "/covers/visual-candidates/k-2.jpg"
    },
    {
      "letter": "K",
      "releaseId": "b4a7d2ed-fecb-48b2-96db-2d4f5161212a",
      "title": "K",
      "artist": "Kula Shaker",
      "detailUrl": "https://musicbrainz.org/release/b4a7d2ed-fecb-48b2-96db-2d4f5161212a",
      "localCoverUrl": "/covers/visual-candidates/k-3.jpg"
    },
    {
      "letter": "K",
      "releaseId": "ee7d69ab-0d3d-4abd-84fe-98bf69359689",
      "title": "K",
      "artist": "Kenneths",
      "detailUrl": "https://musicbrainz.org/release/ee7d69ab-0d3d-4abd-84fe-98bf69359689",
      "localCoverUrl": "/covers/visual-candidates/k-4.jpg"
    },
    {
      "letter": "K",
      "releaseId": "c6e7b2dd-db99-49c5-b32b-f495ab31161c",
      "title": "K",
      "artist": "Lil’ Flip",
      "detailUrl": "https://musicbrainz.org/release/c6e7b2dd-db99-49c5-b32b-f495ab31161c",
      "localCoverUrl": "/covers/visual-candidates/k-5.jpg"
    }
  ],
  "L": [
    {
      "letter": "L",
      "releaseId": "a8152da3-0727-4036-902e-2f66d9f9678b",
      "title": "L",
      "artist": "Todd Pierce",
      "detailUrl": "https://musicbrainz.org/release/a8152da3-0727-4036-902e-2f66d9f9678b",
      "localCoverUrl": "/covers/visual-candidates/l-1.jpg"
    },
    {
      "letter": "L",
      "releaseId": "b32249a6-3e17-4150-aab4-39fdad1d7f4f",
      "title": "L",
      "artist": "LifeMod",
      "detailUrl": "https://musicbrainz.org/release/b32249a6-3e17-4150-aab4-39fdad1d7f4f",
      "localCoverUrl": "/covers/visual-candidates/l-2.jpg"
    },
    {
      "letter": "L",
      "releaseId": "1f754b41-f98b-4d7e-ac2a-b250d47fae62",
      "title": "L",
      "artist": "Madam West",
      "detailUrl": "https://musicbrainz.org/release/1f754b41-f98b-4d7e-ac2a-b250d47fae62",
      "localCoverUrl": "/covers/visual-candidates/l-3.jpg"
    },
    {
      "letter": "L",
      "releaseId": "5d5ce4e4-2915-45dd-b915-0992c23d4a25",
      "title": "L",
      "artist": "Laurels",
      "detailUrl": "https://musicbrainz.org/release/5d5ce4e4-2915-45dd-b915-0992c23d4a25",
      "localCoverUrl": "/covers/visual-candidates/l-4.jpg"
    },
    {
      "letter": "L",
      "releaseId": "dfd148ad-b403-49ba-9be7-837788c43845",
      "title": "L",
      "artist": "Godley & Creme",
      "detailUrl": "https://musicbrainz.org/release/dfd148ad-b403-49ba-9be7-837788c43845",
      "localCoverUrl": "/covers/visual-candidates/l-5.jpg"
    }
  ],
  "M": [
    {
      "letter": "M",
      "releaseId": "65331393-786e-4be6-8a60-4133024febf3",
      "title": "M",
      "artist": "Myrkur",
      "detailUrl": "https://musicbrainz.org/release/65331393-786e-4be6-8a60-4133024febf3",
      "localCoverUrl": "/covers/visual-candidates/m-1.jpg"
    },
    {
      "letter": "M",
      "releaseId": "bdaaee9d-2697-46f3-bd8b-030039a1403b",
      "title": "M",
      "artist": "BIGBANG",
      "detailUrl": "https://musicbrainz.org/release/bdaaee9d-2697-46f3-bd8b-030039a1403b",
      "localCoverUrl": "/covers/visual-candidates/m-4.jpg"
    },
    {
      "letter": "M",
      "releaseId": "4d00213d-c4f3-48ac-aca2-b7b7c8f3a962",
      "title": "M",
      "artist": "Muhsinah",
      "detailUrl": "https://musicbrainz.org/release/4d00213d-c4f3-48ac-aca2-b7b7c8f3a962",
      "localCoverUrl": "/covers/visual-candidates/m-5.jpg"
    }
  ],
  "N": [
    {
      "letter": "N",
      "releaseId": "2c9e53c6-6072-4c48-8c44-45c15fab4ae8",
      "title": "N",
      "artist": "Nodja",
      "detailUrl": "https://musicbrainz.org/release/2c9e53c6-6072-4c48-8c44-45c15fab4ae8",
      "localCoverUrl": "/covers/visual-candidates/n-2.jpg"
    },
    {
      "letter": "N",
      "releaseId": "ba2cfe13-f655-41ca-9232-178753f31c83",
      "title": "N",
      "artist": "Nisennenmondai",
      "detailUrl": "https://musicbrainz.org/release/ba2cfe13-f655-41ca-9232-178753f31c83",
      "localCoverUrl": "/covers/visual-candidates/n-3.jpg"
    },
    {
      "letter": "N",
      "releaseId": "f06088c6-b9fd-4aeb-86ee-1d3f9b213f73",
      "title": "N",
      "artist": "Natasha Luna",
      "detailUrl": "https://musicbrainz.org/release/f06088c6-b9fd-4aeb-86ee-1d3f9b213f73",
      "localCoverUrl": "/covers/visual-candidates/n-4.jpg"
    }
  ],
  "O": [
    {
      "letter": "O",
      "releaseId": "b43c8a60-6cfb-4ef1-82ac-5ac22ac325f5",
      "title": "O",
      "artist": "Cirque du Soleil",
      "detailUrl": "https://musicbrainz.org/release/b43c8a60-6cfb-4ef1-82ac-5ac22ac325f5",
      "localCoverUrl": "/covers/visual-candidates/o-1.jpg"
    },
    {
      "letter": "O",
      "releaseId": "d9645279-cc37-4aea-9083-bd7f45a7afc8",
      "title": "O",
      "artist": "Chłopcy Kontra Basia",
      "detailUrl": "https://musicbrainz.org/release/d9645279-cc37-4aea-9083-bd7f45a7afc8",
      "localCoverUrl": "/covers/visual-candidates/o-2.jpg"
    },
    {
      "letter": "O",
      "releaseId": "74982f1f-fa30-4453-9737-06ffd48b32b6",
      "title": "o",
      "artist": "The Gentle Art of Cooking People",
      "detailUrl": "https://musicbrainz.org/release/74982f1f-fa30-4453-9737-06ffd48b32b6",
      "localCoverUrl": "/covers/visual-candidates/o-5.jpg"
    }
  ],
  "P": [
    {
      "letter": "P",
      "releaseId": "cd096333-e426-4ba3-a1d7-82745bf2ff87",
      "title": "P",
      "artist": "P",
      "detailUrl": "https://musicbrainz.org/release/cd096333-e426-4ba3-a1d7-82745bf2ff87",
      "localCoverUrl": "/covers/visual-candidates/p-2.jpg"
    },
    {
      "letter": "P",
      "releaseId": "873d7515-adf0-47f9-87a9-1ecee09b2ed4",
      "title": "P",
      "artist": "Kaminsky",
      "detailUrl": "https://musicbrainz.org/release/873d7515-adf0-47f9-87a9-1ecee09b2ed4",
      "localCoverUrl": "/covers/visual-candidates/p-3.jpg"
    },
    {
      "letter": "P",
      "releaseId": "71e88c3c-8f64-439d-8908-b7f1d1698187",
      "title": "P",
      "artist": "Deja Voodoo",
      "detailUrl": "https://musicbrainz.org/release/71e88c3c-8f64-439d-8908-b7f1d1698187",
      "localCoverUrl": "/covers/visual-candidates/p-4.jpg"
    },
    {
      "letter": "P",
      "releaseId": "78e50f6e-8be3-409c-a288-19be86a3e901",
      "title": "P",
      "artist": "Prince de Takicardie",
      "detailUrl": "https://musicbrainz.org/release/78e50f6e-8be3-409c-a288-19be86a3e901",
      "localCoverUrl": "/covers/visual-candidates/p-5.jpg"
    }
  ],
  "Q": [
    {
      "letter": "Q",
      "releaseId": "82a5236b-6a20-4750-8a48-810b6ca6ad36",
      "title": "Q",
      "artist": "Cheeze",
      "detailUrl": "https://musicbrainz.org/release/82a5236b-6a20-4750-8a48-810b6ca6ad36",
      "localCoverUrl": "/covers/visual-candidates/q-1.jpg"
    },
    {
      "letter": "Q",
      "releaseId": "f4bf60f7-83af-4fce-8c51-e57ac3f250d2",
      "title": "Q",
      "artist": "Q",
      "detailUrl": "https://musicbrainz.org/release/f4bf60f7-83af-4fce-8c51-e57ac3f250d2",
      "localCoverUrl": "/covers/visual-candidates/q-3.jpg"
    },
    {
      "letter": "Q",
      "releaseId": "5b3f6a49-4417-4f15-ab41-68af6681f2c5",
      "title": "Q",
      "artist": "Hideto Kanai Group",
      "detailUrl": "https://musicbrainz.org/release/5b3f6a49-4417-4f15-ab41-68af6681f2c5",
      "localCoverUrl": "/covers/visual-candidates/q-4.jpg"
    },
    {
      "letter": "Q",
      "releaseId": "bfccee23-a25e-4ebb-b929-fb1de8750411",
      "title": "Q",
      "artist": "Mori Calliope, Gawr Gura",
      "detailUrl": "https://musicbrainz.org/release/bfccee23-a25e-4ebb-b929-fb1de8750411",
      "localCoverUrl": "/covers/visual-candidates/q-5.jpg"
    }
  ],
  "R": [
    {
      "letter": "R",
      "releaseId": "c262d8d7-2ac6-4b9d-9c61-c3c0447ba95a",
      "title": "R",
      "artist": "MintJam, ViViX",
      "detailUrl": "https://musicbrainz.org/release/c262d8d7-2ac6-4b9d-9c61-c3c0447ba95a",
      "localCoverUrl": "/covers/visual-candidates/r-1.jpg"
    },
    {
      "letter": "R",
      "releaseId": "8b236c63-607b-400b-86a4-c31d32cd77fa",
      "title": "r",
      "artist": "Erases Eraser",
      "detailUrl": "https://musicbrainz.org/release/8b236c63-607b-400b-86a4-c31d32cd77fa",
      "localCoverUrl": "/covers/visual-candidates/r-2.jpg"
    },
    {
      "letter": "R",
      "releaseId": "08edd0cd-9014-4c34-81f5-0360e9b61bcd",
      "title": "R",
      "artist": "Roselia",
      "detailUrl": "https://musicbrainz.org/release/08edd0cd-9014-4c34-81f5-0360e9b61bcd",
      "localCoverUrl": "/covers/visual-candidates/r-3.jpg"
    },
    {
      "letter": "R",
      "releaseId": "097d1458-eaa6-441c-b048-4bc0c172e908",
      "title": "R",
      "artist": "규영",
      "detailUrl": "https://musicbrainz.org/release/097d1458-eaa6-441c-b048-4bc0c172e908",
      "localCoverUrl": "/covers/visual-candidates/r-4.jpg"
    },
    {
      "letter": "R",
      "releaseId": "63a1270d-c015-4dec-afe1-3229764b8f36",
      "title": "R",
      "artist": "Acrophilic Project",
      "detailUrl": "https://musicbrainz.org/release/63a1270d-c015-4dec-afe1-3229764b8f36",
      "localCoverUrl": "/covers/visual-candidates/r-5.jpg"
    }
  ],
  "S": [
    {
      "letter": "S",
      "releaseId": "5cfb17ec-d410-4a2d-88b7-3f651a8aa2a5",
      "title": "s",
      "artist": "Erases Eraser",
      "detailUrl": "https://musicbrainz.org/release/5cfb17ec-d410-4a2d-88b7-3f651a8aa2a5",
      "localCoverUrl": "/covers/visual-candidates/s-1.jpg"
    },
    {
      "letter": "S",
      "releaseId": "e7beca26-29bc-40bc-91e3-a8433be6fa19",
      "title": "S",
      "artist": "Team.ねこかん[猫]",
      "detailUrl": "https://musicbrainz.org/release/e7beca26-29bc-40bc-91e3-a8433be6fa19",
      "localCoverUrl": "/covers/visual-candidates/s-2.jpg"
    },
    {
      "letter": "S",
      "releaseId": "4c3d985c-8047-471c-ba72-73a3a816d150",
      "title": "S",
      "artist": "Chaos Chaos",
      "detailUrl": "https://musicbrainz.org/release/4c3d985c-8047-471c-ba72-73a3a816d150",
      "localCoverUrl": "/covers/visual-candidates/s-4.jpg"
    },
    {
      "letter": "S",
      "releaseId": "3f567030-9a71-4bf6-bd5a-719a225eac7e",
      "title": "S",
      "artist": "Mesmur",
      "detailUrl": "https://musicbrainz.org/release/3f567030-9a71-4bf6-bd5a-719a225eac7e",
      "localCoverUrl": "/covers/visual-candidates/s-5.jpg"
    }
  ],
  "T": [
    {
      "letter": "T",
      "releaseId": "a42644c9-f2ab-4ee3-9687-f86d2c606972",
      "title": "T",
      "artist": "Tunguska Electronic Music Society",
      "detailUrl": "https://musicbrainz.org/release/a42644c9-f2ab-4ee3-9687-f86d2c606972",
      "localCoverUrl": "/covers/visual-candidates/t-1.jpg"
    },
    {
      "letter": "T",
      "releaseId": "99dafd60-3c64-47ba-9e48-81207bd0adab",
      "title": "T",
      "artist": "Industrie 67",
      "detailUrl": "https://musicbrainz.org/release/99dafd60-3c64-47ba-9e48-81207bd0adab",
      "localCoverUrl": "/covers/visual-candidates/t-2.jpg"
    },
    {
      "letter": "T",
      "releaseId": "fea4952f-bf9b-4c5c-9319-16b1202bf318",
      "title": "T",
      "artist": "Teflon Brothers",
      "detailUrl": "https://musicbrainz.org/release/fea4952f-bf9b-4c5c-9319-16b1202bf318",
      "localCoverUrl": "/covers/visual-candidates/t-3.jpg"
    },
    {
      "letter": "T",
      "releaseId": "3d708c78-82c7-4f26-82ae-fb398b597509",
      "title": "T",
      "artist": "Tásler",
      "detailUrl": "https://musicbrainz.org/release/3d708c78-82c7-4f26-82ae-fb398b597509",
      "localCoverUrl": "/covers/visual-candidates/t-4.jpg"
    },
    {
      "letter": "T",
      "releaseId": "43093ac0-49a9-4d62-88d3-6d983f847e01",
      "title": "T",
      "artist": "Jakob Juhkam",
      "detailUrl": "https://musicbrainz.org/release/43093ac0-49a9-4d62-88d3-6d983f847e01",
      "localCoverUrl": "/covers/visual-candidates/t-5.jpg"
    }
  ],
  "U": [
    {
      "letter": "U",
      "releaseId": "46f54151-bdf9-4b08-88c9-8c62b776780e",
      "title": "U",
      "artist": "Alix Perez",
      "detailUrl": "https://musicbrainz.org/release/46f54151-bdf9-4b08-88c9-8c62b776780e",
      "localCoverUrl": "/covers/visual-candidates/u-2.jpg"
    },
    {
      "letter": "U",
      "releaseId": "56680eb3-6b8b-478c-911a-98efe4cda3eb",
      "title": "U",
      "artist": "DOUBLE",
      "detailUrl": "https://musicbrainz.org/release/56680eb3-6b8b-478c-911a-98efe4cda3eb",
      "localCoverUrl": "/covers/visual-candidates/u-3.jpg"
    },
    {
      "letter": "U",
      "releaseId": "f21a69e1-7d28-4a8a-bf68-131daf6fedf7",
      "title": "U",
      "artist": "Sela",
      "detailUrl": "https://musicbrainz.org/release/f21a69e1-7d28-4a8a-bf68-131daf6fedf7",
      "localCoverUrl": "/covers/visual-candidates/u-4.jpg"
    },
    {
      "letter": "U",
      "releaseId": "ee630e52-5354-4279-8d51-60df17efaa41",
      "title": "U",
      "artist": "L'Ham de Foc",
      "detailUrl": "https://musicbrainz.org/release/ee630e52-5354-4279-8d51-60df17efaa41",
      "localCoverUrl": "/covers/visual-candidates/u-5.jpg"
    }
  ],
  "V": [
    {
      "letter": "V",
      "releaseId": "80c43523-38c3-41d7-997c-ad41f46b12d1",
      "title": "V",
      "artist": "Vanessa Hudgens",
      "detailUrl": "https://musicbrainz.org/release/80c43523-38c3-41d7-997c-ad41f46b12d1",
      "localCoverUrl": "/covers/visual-candidates/v-1.jpg"
    },
    {
      "letter": "V",
      "releaseId": "12e2a7fd-5105-4a45-8196-88bc8b01ca8d",
      "title": "V",
      "artist": "The Flight of Sleipnir",
      "detailUrl": "https://musicbrainz.org/release/12e2a7fd-5105-4a45-8196-88bc8b01ca8d",
      "localCoverUrl": "/covers/visual-candidates/v-2.jpg"
    },
    {
      "letter": "V",
      "releaseId": "fa9081ba-f403-4384-9b40-b428423f36f6",
      "title": "V",
      "artist": "NoGoD",
      "detailUrl": "https://musicbrainz.org/release/fa9081ba-f403-4384-9b40-b428423f36f6",
      "localCoverUrl": "/covers/visual-candidates/v-3.jpg"
    },
    {
      "letter": "V",
      "releaseId": "048912ff-1374-411d-b863-e0c506053dda",
      "title": "V",
      "artist": "Wavves",
      "detailUrl": "https://musicbrainz.org/release/048912ff-1374-411d-b863-e0c506053dda",
      "localCoverUrl": "/covers/visual-candidates/v-4.jpg"
    }
  ],
  "W": [
    {
      "letter": "W",
      "releaseId": "2f7ecc12-aef3-4e56-85c6-3fada94f4496",
      "title": "W",
      "artist": "Jean-Luc Guionnet, Benjamin Duboc",
      "detailUrl": "https://musicbrainz.org/release/2f7ecc12-aef3-4e56-85c6-3fada94f4496",
      "localCoverUrl": "/covers/visual-candidates/w-1.jpg"
    },
    {
      "letter": "W",
      "releaseId": "1448c2c6-f8d2-4621-84f4-f5120c3541b0",
      "title": "W",
      "artist": "Sikboy",
      "detailUrl": "https://musicbrainz.org/release/1448c2c6-f8d2-4621-84f4-f5120c3541b0",
      "localCoverUrl": "/covers/visual-candidates/w-2.jpg"
    },
    {
      "letter": "W",
      "releaseId": "08e8ca73-7ab4-40ad-8105-ffce3c6badf1",
      "title": "W",
      "artist": "The Aether",
      "detailUrl": "https://musicbrainz.org/release/08e8ca73-7ab4-40ad-8105-ffce3c6badf1",
      "localCoverUrl": "/covers/visual-candidates/w-4.jpg"
    },
    {
      "letter": "W",
      "releaseId": "cb74e9a4-863e-467e-810e-bbcd38edac8f",
      "title": "W",
      "artist": "Populous",
      "detailUrl": "https://musicbrainz.org/release/cb74e9a4-863e-467e-810e-bbcd38edac8f",
      "localCoverUrl": "/covers/visual-candidates/w-5.jpg"
    }
  ],
  "X": [
    {
      "letter": "X",
      "releaseId": "bba766ea-4fc3-4eda-bac1-60f38f502455",
      "title": "X",
      "artist": "United Jazz + Rock Ensemble",
      "detailUrl": "https://musicbrainz.org/release/bba766ea-4fc3-4eda-bac1-60f38f502455",
      "localCoverUrl": "/covers/visual-candidates/x-1.jpg"
    },
    {
      "letter": "X",
      "releaseId": "e8cc89c7-caeb-4703-9994-dbe0a2386cd7",
      "title": "X",
      "artist": "AWeX",
      "detailUrl": "https://musicbrainz.org/release/e8cc89c7-caeb-4703-9994-dbe0a2386cd7",
      "localCoverUrl": "/covers/visual-candidates/x-2.jpg"
    },
    {
      "letter": "X",
      "releaseId": "0d7ab292-06b6-4889-b3d5-e7e5f278b077",
      "title": "X",
      "artist": "Lucki Eck$",
      "detailUrl": "https://musicbrainz.org/release/0d7ab292-06b6-4889-b3d5-e7e5f278b077",
      "localCoverUrl": "/covers/visual-candidates/x-3.jpg"
    },
    {
      "letter": "X",
      "releaseId": "5ae5627d-bff7-42e5-9330-a3fb8e25cd00",
      "title": "X",
      "artist": "INXS",
      "detailUrl": "https://musicbrainz.org/release/5ae5627d-bff7-42e5-9330-a3fb8e25cd00",
      "localCoverUrl": "/covers/visual-candidates/x-4.jpg"
    },
    {
      "letter": "X",
      "releaseId": "c6a1da27-7de4-4abe-bc97-ddcc441ce925",
      "title": "X",
      "artist": "Big Russian Boss",
      "detailUrl": "https://musicbrainz.org/release/c6a1da27-7de4-4abe-bc97-ddcc441ce925",
      "localCoverUrl": "/covers/visual-candidates/x-5.jpg"
    }
  ],
  "Y": [
    {
      "letter": "Y",
      "releaseId": "941a13cf-6fcb-4cf0-b0ec-1f39691680ca",
      "title": "Y",
      "artist": "7dove",
      "detailUrl": "https://musicbrainz.org/release/941a13cf-6fcb-4cf0-b0ec-1f39691680ca",
      "localCoverUrl": "/covers/visual-candidates/y-1.jpg"
    },
    {
      "letter": "Y",
      "releaseId": "da58ba92-433c-42f3-a5da-b759490c7662",
      "title": "Y",
      "artist": "Yous Mc",
      "detailUrl": "https://musicbrainz.org/release/da58ba92-433c-42f3-a5da-b759490c7662",
      "localCoverUrl": "/covers/visual-candidates/y-3.jpg"
    },
    {
      "letter": "Y",
      "releaseId": "4d3d05a1-59bb-4991-b999-4a2c66a1dae4",
      "title": "Y",
      "artist": "Lydmor",
      "detailUrl": "https://musicbrainz.org/release/4d3d05a1-59bb-4991-b999-4a2c66a1dae4",
      "localCoverUrl": "/covers/visual-candidates/y-4.jpg"
    },
    {
      "letter": "Y",
      "releaseId": "5e2368db-2c67-42f6-b979-efee8adb9490",
      "title": "Y",
      "artist": "Yeung Human",
      "detailUrl": "https://musicbrainz.org/release/5e2368db-2c67-42f6-b979-efee8adb9490",
      "localCoverUrl": "/covers/visual-candidates/y-5.jpg"
    }
  ],
  "Z": [
    {
      "letter": "Z",
      "releaseId": "e10ee6a4-5e4f-48fe-bf77-831f3a5c6019",
      "title": "Z",
      "artist": "ZONE",
      "detailUrl": "https://musicbrainz.org/release/e10ee6a4-5e4f-48fe-bf77-831f3a5c6019",
      "localCoverUrl": "/covers/visual-candidates/z-1.jpg"
    },
    {
      "letter": "Z",
      "releaseId": "57b3596e-dff3-489e-83c2-9efe206d65d3",
      "title": "Z",
      "artist": "Gonzales",
      "detailUrl": "https://musicbrainz.org/release/57b3596e-dff3-489e-83c2-9efe206d65d3",
      "localCoverUrl": "/covers/visual-candidates/z-2.jpg"
    },
    {
      "letter": "Z",
      "releaseId": "5530b151-95de-436d-8a81-699c8a819c23",
      "title": "Z",
      "artist": "Cummi Flu",
      "detailUrl": "https://musicbrainz.org/release/5530b151-95de-436d-8a81-699c8a819c23",
      "localCoverUrl": "/covers/visual-candidates/z-4.jpg"
    },
    {
      "letter": "Z",
      "releaseId": "81a64f02-8c24-4cc3-a2e9-e8693cbb279e",
      "title": "Z",
      "artist": "Vanilin",
      "detailUrl": "https://musicbrainz.org/release/81a64f02-8c24-4cc3-a2e9-e8693cbb279e",
      "localCoverUrl": "/covers/visual-candidates/z-5.jpg"
    }
  ]
};

export const GENERATED_VISUAL_CANDIDATE_COUNT = 106;
